### ISSUE TITLE
New bindings for EDIT/DELETE tribe

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-rs#50]
We need new bindings for EDIT/DELETE tribe:

EDIT TRIBE:
- Should edit the tribe in the tribes server (image, name, description, private and listed configuration, etc)

DELETE TRIBE:
- Should delete the tribe from the tribes server and send the `groupDelete (22)` message to all members
- Should publish to LSP to delete all messages in this tribe so It's not restore again when fetching new messages

LEAVE TRIBE/ TRIBE KICK
- We should think about publishing to LSP and deleting all messages in a tribe when leaving a tribe or being kicked from it

Asking for this since we will start using V2 and creating new tribes so having the ability to edit and delete them would be useful. 

@Evanfeenstra tagging you here since I can't assign tickets in this repo.

**Comment by Evanfeenstra** [comment]
ready to test on regtest https://github.com/stakwork/sphinx/commit/c4d515205a5503de59a3310b6c82a3065241f98d
