### ISSUE TITLE
Clear badge count

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-rs#55]
When mixer receives a setRead message it should calculate badge and just if it's 0 it should send a push notification with no content (empty text) and badge = 0. 

This will help in the following situation:
- User has no new messages
- User receives a message a badge is set to 1
- User opens that chat in a different client (like Mac)
- The app calls setRead and sets all messages as read
- The LSP send the push with no content and badge = 0
- Mobile apps will reset the badge so it won't show new messages anymore

**Comment by Evanfeenstra** [comment]
https://github.com/stakwork/sphinx/commit/4c41ad063324d8235f9cba035332670e8685da56
