### ISSUE TITLE
Deep links changes

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-rs#57]
We need to change all deep links from `sphinx.chat://` to `sphinx.chat.v2://` since otherwise they will conflict with V1 app

I think the only place where you need to change that is in the new tribes server directory but let me know if you can think of another place where you are using deep links in V2 servers

As this needs to be done on server and app side together, let me know when you have the changes ready so I can prepare the iOS/Mac/Android ones and we can release everything together

@Evanfeenstra

**Comment by Evanfeenstra** [comment]
dont we want a deeplink to open the sphinx.chat webpage if the user doesn't have an app installed?

**Comment by tomastiminskas** [comment]
That's called universal links and we have implemented that for jitsi calls already on V1. But for the rest of the actions we are using deep links (tribe join buttons, login buttons on ppl and bounties site, etc. So for now changing the scheme on v2 tribes server join buttons would be enough. 

And then we can decide if we use deep links or universal links for the rest.
